import type { Scenario } from "../types";

export const scenarios: Scenario[] = [
  {
    id: "shopping",
    title: "買い物",
    description: "安さ・時間・混雑を比較し、近隣の空いている選択肢も提案",
    icon: "Cart",
    insight: "支払額だけでなく、時間・混雑・近隣資源の活用まで含めると、納得できる最適解が変わります。",
    options: [
      {
        id: "discount-market",
        name: "遠い安売りスーパー",
        shortName: "安売り店",
        paymentCost: 4800,
        travelMinutes: 45,
        workMinutes: 35,
        crowd: "高",
        fatigue: "高",
        risk: "中",
        fatigueBaseCost: 420,
        riskBaseCost: 250,
        congestionBaseCost: 420,
        benefitBonus: 1720,
        urbanImpact: { congestionAvoidance: 18, alternativeUse: 15, travelReduction: 12, score: 16 },
        facts: ["支払額 4,800円", "移動45分", "混雑 高", "疲労 高"],
        reason: "価格は安い一方、移動時間と混雑負荷が高く、人気店への集中にもつながるため、今日の条件ではLife ROIが下がります。",
        caution: "移動と混雑の負荷が大きく、忙しい日ほど実質生活コストが上がります。",
        fit: "自由時間に余裕があり、まとめて安く買いたい人"
      },
      {
        id: "local-market",
        name: "近所のスーパー",
        shortName: "近所の店",
        paymentCost: 5300,
        travelMinutes: 10,
        workMinutes: 25,
        crowd: "中",
        fatigue: "低",
        risk: "低",
        fatigueBaseCost: 150,
        riskBaseCost: 100,
        congestionBaseCost: 180,
        benefitBonus: 760,
        urbanImpact: { congestionAvoidance: 58, alternativeUse: 62, travelReduction: 78, score: 66 },
        facts: ["支払額 5,300円", "移動10分", "混雑 中", "リスク 低"],
        reason: "支払額は最安ではありませんが、移動時間と疲労が少なく、生活圏内で完結できるため個人価値と都市価値のバランスが良い選択です。",
        caution: "価格面では遠い安売り店に劣るため、時間価値が低い日は順位が下がることがあります。",
        fit: "仕事後に短時間で確実に買い物を済ませたい人"
      },
      {
        id: "online-grocery",
        name: "ネットスーパー",
        shortName: "ネット",
        paymentCost: 5800,
        feeCost: 330,
        travelMinutes: 0,
        workMinutes: 15,
        crowd: "なし",
        fatigue: "低",
        risk: "中",
        fatigueBaseCost: 120,
        riskBaseCost: 260,
        congestionBaseCost: 40,
        benefitBonus: 820,
        urbanImpact: { congestionAvoidance: 82, alternativeUse: 45, travelReduction: 96, score: 74 },
        facts: ["支払額 5,800円", "送料330円", "選択15分", "移動なし"],
        reason: "送料は発生しますが、移動時間が不要で、忙しい日や子育て中の時間確保に有効です。店舗混雑を避ける選択にもなります。",
        caution: "欠品や配送枠の制約があり、当日すぐに必要な買い物では注意が必要です。",
        fit: "自由時間が少なく、家で受け取りたい人"
      },
      {
        id: "quiet-nearby-market",
        name: "近隣の空いている店舗",
        shortName: "空いている店",
        paymentCost: 5550,
        feeCost: 0,
        travelMinutes: 8,
        workMinutes: 22,
        crowd: "低",
        fatigue: "低",
        risk: "低",
        fatigueBaseCost: 90,
        riskBaseCost: 90,
        congestionBaseCost: 55,
        benefitBonus: 980,
        urbanImpact: { congestionAvoidance: 92, alternativeUse: 94, travelReduction: 84, score: 91 },
        facts: ["支払額 5,550円", "移動8分", "混雑 低", "都市分散効果 高"],
        reason: "移動時間と混雑負荷が低く、あなたの時間価値では合理的です。人気店への集中を避け、近隣の空いている店舗を活用できるため都市分散効果も高い選択です。",
        caution: "特売品や品ぞろえは人気の大型店より限られる場合があります。",
        fit: "短時間で買い物を済ませ、混雑も避けたい人"
      }
    ]
  },
  {
    id: "admin",
    title: "行政手続き",
    description: "窓口・オンライン・郵送を比較し、手戻りや待ち時間を削減",
    icon: "Landmark",
    insight: "今回はオンライン申請が最適です。窓口は確実性が高い一方、移動・待ち時間が重くなります。",
    options: [
      {
        id: "ward-office",
        name: "区役所窓口",
        shortName: "窓口",
        paymentCost: 420,
        travelMinutes: 35,
        waitMinutes: 45,
        workMinutes: 20,
        crowd: "高",
        fatigue: "中",
        risk: "低",
        fatigueBaseCost: 280,
        riskBaseCost: 90,
        congestionBaseCost: 320,
        benefitBonus: 500,
        urbanImpact: { congestionAvoidance: 20, alternativeUse: 25, travelReduction: 18, score: 21 },
        facts: ["交通費420円", "待ち45分", "確認しやすい", "確実性 高"],
        reason: "対面で確認できるため安心ですが、移動と待ち時間で実質生活コストが上がります。",
        caution: "混雑時間帯は待ち時間がさらに増えます。",
        fit: "不備が心配で、その場で確認したい人"
      },
      {
        id: "online-apply",
        name: "オンライン申請",
        shortName: "オンライン",
        paymentCost: 0,
        travelMinutes: 0,
        waitMinutes: 0,
        workMinutes: 25,
        crowd: "なし",
        fatigue: "低",
        risk: "中",
        fatigueBaseCost: 80,
        riskBaseCost: 200,
        congestionBaseCost: 20,
        benefitBonus: 780,
        urbanImpact: { congestionAvoidance: 95, alternativeUse: 82, travelReduction: 100, score: 92 },
        facts: ["交通費0円", "移動なし", "手続き25分", "リスク 中"],
        reason: "移動・待ち時間がなく、忙しい日でも手取り時間を残せます。窓口混雑を避け、公共サービスの利用分散にもつながります。",
        caution: "添付書類の不備には注意が必要です。",
        fit: "スマホやPCで手続きを完結したい人"
      },
      {
        id: "mail-apply",
        name: "郵送申請",
        shortName: "郵送",
        paymentCost: 210,
        travelMinutes: 10,
        waitMinutes: 0,
        workMinutes: 35,
        crowd: "低",
        fatigue: "低",
        risk: "高",
        fatigueBaseCost: 100,
        riskBaseCost: 420,
        congestionBaseCost: 45,
        benefitBonus: 430,
        urbanImpact: { congestionAvoidance: 78, alternativeUse: 72, travelReduction: 70, score: 74 },
        facts: ["郵送210円", "作業35分", "手戻り 高", "待ちなし"],
        reason: "窓口に行かずに済みますが、書類不備の手戻りリスクがあります。",
        caution: "処理完了までの日数が読みづらい点があります。",
        fit: "急ぎではなく、紙で確認しながら進めたい人"
      }
    ]
  },
  {
    id: "mobility",
    title: "移動",
    description: "時間・運賃・混雑・疲労を比較し、無理のない移動を提案",
    icon: "Train",
    insight: "時間価値が高い日は、単純な運賃よりも到着確実性と疲労の小ささが効きます。",
    options: [
      {
        id: "train",
        name: "電車",
        shortName: "電車",
        paymentCost: 240,
        travelMinutes: 32,
        waitMinutes: 7,
        workMinutes: 0,
        crowd: "高",
        fatigue: "中",
        risk: "低",
        fatigueBaseCost: 180,
        riskBaseCost: 80,
        congestionBaseCost: 300,
        benefitBonus: 520,
        urbanImpact: { congestionAvoidance: 25, alternativeUse: 35, travelReduction: 62, score: 40 },
        facts: ["運賃240円", "39分", "混雑 高", "定時性 高"],
        reason: "定時性が高く、支払額も低めです。",
        caution: "混雑による疲労が出やすい時間帯があります。",
        fit: "コストと確実性のバランスを取りたい人"
      },
      {
        id: "taxi",
        name: "タクシー",
        shortName: "タクシー",
        paymentCost: 2600,
        travelMinutes: 18,
        waitMinutes: 3,
        workMinutes: 0,
        crowd: "なし",
        fatigue: "低",
        risk: "中",
        fatigueBaseCost: 80,
        riskBaseCost: 180,
        congestionBaseCost: 70,
        benefitBonus: 680,
        urbanImpact: { congestionAvoidance: 85, alternativeUse: 45, travelReduction: 18, score: 54 },
        facts: ["運賃2,600円", "21分", "疲労 低", "雨に強い"],
        reason: "支払額は高い一方、時間と疲労を大きく削減します。",
        caution: "渋滞で所要時間が変動します。",
        fit: "遅刻リスクや移動疲れを避けたい人"
      },
      {
        id: "walk",
        name: "徒歩",
        shortName: "徒歩",
        paymentCost: 0,
        travelMinutes: 55,
        workMinutes: 0,
        crowd: "なし",
        fatigue: "高",
        risk: "中",
        fatigueBaseCost: 440,
        riskBaseCost: 160,
        congestionBaseCost: 10,
        benefitBonus: 250,
        urbanImpact: { congestionAvoidance: 96, alternativeUse: 70, travelReduction: 100, score: 90 },
        facts: ["支払0円", "55分", "疲労 高", "天候影響あり"],
        reason: "支払額はゼロですが、時間と疲労のコストが大きくなります。",
        caution: "雨天や荷物が多い日は向きません。",
        fit: "運動を兼ねたい余裕のある日"
      },
      {
        id: "bike",
        name: "自転車",
        shortName: "自転車",
        paymentCost: 150,
        travelMinutes: 24,
        workMinutes: 0,
        crowd: "なし",
        fatigue: "中",
        risk: "中",
        fatigueBaseCost: 200,
        riskBaseCost: 190,
        congestionBaseCost: 20,
        benefitBonus: 560,
        urbanImpact: { congestionAvoidance: 92, alternativeUse: 86, travelReduction: 96, score: 91 },
        facts: ["利用料150円", "24分", "混雑なし", "天候影響あり"],
        reason: "移動時間と支払額のバランスが良い選択肢です。",
        caution: "雨天と駐輪場所の制約があります。",
        fit: "短距離を軽く移動したい人"
      }
    ]
  },
  {
    id: "family",
    title: "子育ておでかけ",
    description: "天気・混雑・移動負荷から、親子に無理のない行き先を提案",
    icon: "Baby",
    insight: "今日は雨の可能性があり、子連れ移動の負荷が高いため、近所の児童館が高ROIです。",
    options: [
      {
        id: "big-park",
        name: "遠い大型公園",
        shortName: "大型公園",
        paymentCost: 0,
        feeCost: 520,
        travelMinutes: 55,
        workMinutes: 20,
        crowd: "中",
        fatigue: "高",
        risk: "高",
        fatigueBaseCost: 620,
        riskBaseCost: 480,
        congestionBaseCost: 180,
        benefitBonus: 620,
        urbanImpact: { congestionAvoidance: 42, alternativeUse: 35, travelReduction: 18, score: 31 },
        facts: ["入場料0円", "交通費520円", "雨に弱い", "子連れ負荷 高"],
        reason: "無料で遊べますが、移動負荷と天気影響が大きい選択肢です。",
        caution: "雨の可能性がある日は手戻りリスクが高まります。",
        fit: "晴れていて半日たっぷり使える日"
      },
      {
        id: "indoor",
        name: "有料屋内施設",
        shortName: "屋内施設",
        paymentCost: 2800,
        feeCost: 360,
        travelMinutes: 30,
        workMinutes: 15,
        crowd: "高",
        fatigue: "中",
        risk: "低",
        fatigueBaseCost: 310,
        riskBaseCost: 120,
        congestionBaseCost: 330,
        benefitBonus: 780,
        urbanImpact: { congestionAvoidance: 22, alternativeUse: 38, travelReduction: 35, score: 30 },
        facts: ["入場料2,800円", "雨に強い", "混雑 高", "満足度 高"],
        reason: "費用はかかりますが、天気に左右されず遊びの満足度が高いです。",
        caution: "休日は混雑で滞在満足度が落ちる可能性があります。",
        fit: "予算よりも確実に楽しめることを重視する家族"
      },
      {
        id: "children-center",
        name: "近所の児童館",
        shortName: "児童館",
        paymentCost: 0,
        travelMinutes: 12,
        workMinutes: 10,
        crowd: "中",
        fatigue: "低",
        risk: "低",
        fatigueBaseCost: 110,
        riskBaseCost: 80,
        congestionBaseCost: 90,
        benefitBonus: 820,
        urbanImpact: { congestionAvoidance: 82, alternativeUse: 94, travelReduction: 88, score: 88 },
        facts: ["入場料0円", "移動12分", "雨に強い", "負荷 低"],
        reason: "費用・移動・天気リスクのバランスが良く、親の疲労を抑えられます。近隣の公共資源を活用し、人気施設への集中を避ける選択にもなります。",
        caution: "大型施設ほどの特別感はありません。",
        fit: "短時間で安全に過ごしたい子育て世帯"
      }
    ]
  }
];
