import type { Scenario } from "../types";

export const scenarios: Scenario[] = [
  {
    id: "shopping",
    title: "買い物",
    description: "遠い安売り店、近所の店、ネットスーパーを比較",
    icon: "Cart",
    insight: "支払額だけなら遠い安売り店が安いが、時間価値を入れると最適解が変わります。",
    options: [
      {
        id: "discount-market",
        name: "遠い安売りスーパー",
        shortName: "安売り店",
        paymentCost: 4800,
        travelMinutes: 45,
        workMinutes: 35,
        crowd: "高",
        fatigue: "高",
        risk: "中",
        fatigueBaseCost: 420,
        riskBaseCost: 250,
        benefitBonus: 1720,
        facts: ["支払額 4,800円", "移動45分", "混雑 高", "疲労 高"],
        reason: "支払額は最も低く、時間価値が低い日や買い回りを楽しめる日は合理的です。",
        caution: "移動と混雑の負荷が大きく、忙しい日ほど実質生活コストが上がります。",
        fit: "自由時間に余裕があり、まとめて安く買いたい人"
      },
      {
        id: "local-market",
        name: "近所のスーパー",
        shortName: "近所の店",
        paymentCost: 5300,
        travelMinutes: 10,
        workMinutes: 25,
        crowd: "中",
        fatigue: "低",
        risk: "低",
        fatigueBaseCost: 150,
        riskBaseCost: 100,
        benefitBonus: 760,
        facts: ["支払額 5,300円", "移動10分", "混雑 中", "リスク 低"],
        reason: "支払額は最安ではありませんが、移動時間が短く、混雑・疲労・手戻りリスクが低いため高いLife ROIになります。",
        caution: "価格面では遠い安売り店に劣るため、時間価値が低い日は順位が下がることがあります。",
        fit: "仕事後に短時間で確実に買い物を済ませたい人"
      },
      {
        id: "online-grocery",
        name: "ネットスーパー",
        shortName: "ネット",
        paymentCost: 5800,
        feeCost: 330,
        travelMinutes: 0,
        workMinutes: 15,
        crowd: "なし",
        fatigue: "低",
        risk: "中",
        fatigueBaseCost: 120,
        riskBaseCost: 260,
        benefitBonus: 820,
        facts: ["支払額 5,800円", "送料330円", "選択15分", "移動なし"],
        reason: "送料は発生しますが、移動時間が不要で、子育て中や仕事後の時間確保に有効です。",
        caution: "欠品や配送枠の制約があり、当日すぐに必要な買い物では注意が必要です。",
        fit: "自由時間が少なく、家で受け取りたい人"
      },
      {
        id: "bulk-delivery",
        name: "まとめ買い配送",
        shortName: "配送",
        paymentCost: 6200,
        feeCost: 0,
        travelMinutes: 0,
        workMinutes: 10,
        crowd: "なし",
        fatigue: "低",
        risk: "低",
        fatigueBaseCost: 95,
        riskBaseCost: 120,
        benefitBonus: 900,
        facts: ["支払額 6,200円", "送料0円", "選択10分", "リスク 低"],
        reason: "支払額は高めでも、移動・混雑・手戻りを抑えられ、忙しい日の手取り時間を最大化します。",
        caution: "少量購入では割高に見えやすいため、週次のまとめ買いに向いています。",
        fit: "買い物回数を減らし、週末の時間を守りたい人"
      }
    ]
  },
  {
    id: "admin",
    title: "行政手続き",
    description: "窓口、オンライン、郵送を比較",
    icon: "Landmark",
    insight: "今回はオンライン申請が最適です。窓口は確実性が高い一方、移動・待ち時間が重くなります。",
    options: [
      {
        id: "ward-office",
        name: "区役所窓口",
        shortName: "窓口",
        paymentCost: 420,
        travelMinutes: 35,
        waitMinutes: 45,
        workMinutes: 20,
        crowd: "高",
        fatigue: "中",
        risk: "低",
        fatigueBaseCost: 280,
        riskBaseCost: 90,
        benefitBonus: 500,
        facts: ["交通費420円", "待ち45分", "確認しやすい", "確実性 高"],
        reason: "対面で確認できるため安心ですが、移動と待ち時間で実質生活コストが上がります。",
        caution: "混雑時間帯は待ち時間がさらに増えます。",
        fit: "不備が心配で、その場で確認したい人"
      },
      {
        id: "online-apply",
        name: "オンライン申請",
        shortName: "オンライン",
        paymentCost: 0,
        travelMinutes: 0,
        waitMinutes: 0,
        workMinutes: 25,
        crowd: "なし",
        fatigue: "低",
        risk: "中",
        fatigueBaseCost: 80,
        riskBaseCost: 200,
        benefitBonus: 780,
        facts: ["交通費0円", "移動なし", "手続き25分", "リスク 中"],
        reason: "移動・待ち時間がなく、忙しい日でも手取り時間を残せます。",
        caution: "添付書類の不備には注意が必要です。",
        fit: "スマホやPCで手続きを完結したい人"
      },
      {
        id: "mail-apply",
        name: "郵送申請",
        shortName: "郵送",
        paymentCost: 210,
        travelMinutes: 10,
        waitMinutes: 0,
        workMinutes: 35,
        crowd: "低",
        fatigue: "低",
        risk: "高",
        fatigueBaseCost: 100,
        riskBaseCost: 420,
        benefitBonus: 430,
        facts: ["郵送210円", "作業35分", "手戻り 高", "待ちなし"],
        reason: "窓口に行かずに済みますが、書類不備の手戻りリスクがあります。",
        caution: "処理完了までの日数が読みづらい点があります。",
        fit: "急ぎではなく、紙で確認しながら進めたい人"
      }
    ]
  },
  {
    id: "mobility",
    title: "移動",
    description: "電車、タクシー、徒歩、自転車を比較",
    icon: "Train",
    insight: "時間価値が高い日は、単純な運賃よりも到着確実性と疲労の小ささが効きます。",
    options: [
      {
        id: "train",
        name: "電車",
        shortName: "電車",
        paymentCost: 240,
        travelMinutes: 32,
        waitMinutes: 7,
        workMinutes: 0,
        crowd: "高",
        fatigue: "中",
        risk: "低",
        fatigueBaseCost: 180,
        riskBaseCost: 80,
        benefitBonus: 520,
        facts: ["運賃240円", "39分", "混雑 高", "定時性 高"],
        reason: "定時性が高く、支払額も低めです。",
        caution: "混雑による疲労が出やすい時間帯があります。",
        fit: "コストと確実性のバランスを取りたい人"
      },
      {
        id: "taxi",
        name: "タクシー",
        shortName: "タクシー",
        paymentCost: 2600,
        travelMinutes: 18,
        waitMinutes: 3,
        workMinutes: 0,
        crowd: "なし",
        fatigue: "低",
        risk: "中",
        fatigueBaseCost: 80,
        riskBaseCost: 180,
        benefitBonus: 680,
        facts: ["運賃2,600円", "21分", "疲労 低", "雨に強い"],
        reason: "支払額は高い一方、時間と疲労を大きく削減します。",
        caution: "渋滞で所要時間が変動します。",
        fit: "遅刻リスクや移動疲れを避けたい人"
      },
      {
        id: "walk",
        name: "徒歩",
        shortName: "徒歩",
        paymentCost: 0,
        travelMinutes: 55,
        workMinutes: 0,
        crowd: "なし",
        fatigue: "高",
        risk: "中",
        fatigueBaseCost: 440,
        riskBaseCost: 160,
        benefitBonus: 250,
        facts: ["支払0円", "55分", "疲労 高", "天候影響あり"],
        reason: "支払額はゼロですが、時間と疲労のコストが大きくなります。",
        caution: "雨天や荷物が多い日は向きません。",
        fit: "運動を兼ねたい余裕のある日"
      },
      {
        id: "bike",
        name: "自転車",
        shortName: "自転車",
        paymentCost: 150,
        travelMinutes: 24,
        workMinutes: 0,
        crowd: "なし",
        fatigue: "中",
        risk: "中",
        fatigueBaseCost: 200,
        riskBaseCost: 190,
        benefitBonus: 560,
        facts: ["利用料150円", "24分", "混雑なし", "天候影響あり"],
        reason: "移動時間と支払額のバランスが良い選択肢です。",
        caution: "雨天と駐輪場所の制約があります。",
        fit: "短距離を軽く移動したい人"
      }
    ]
  },
  {
    id: "family",
    title: "子育ておでかけ",
    description: "無料公園、屋内施設、児童館を比較",
    icon: "Baby",
    insight: "今日は雨の可能性があり、子連れ移動の負荷が高いため、近所の児童館が高ROIです。",
    options: [
      {
        id: "big-park",
        name: "遠い大型公園",
        shortName: "大型公園",
        paymentCost: 0,
        feeCost: 520,
        travelMinutes: 55,
        workMinutes: 20,
        crowd: "中",
        fatigue: "高",
        risk: "高",
        fatigueBaseCost: 620,
        riskBaseCost: 480,
        benefitBonus: 620,
        facts: ["入場料0円", "交通費520円", "雨に弱い", "子連れ負荷 高"],
        reason: "無料で遊べますが、移動負荷と天気影響が大きい選択肢です。",
        caution: "雨の可能性がある日は手戻りリスクが高まります。",
        fit: "晴れていて半日たっぷり使える日"
      },
      {
        id: "indoor",
        name: "有料屋内施設",
        shortName: "屋内施設",
        paymentCost: 2800,
        feeCost: 360,
        travelMinutes: 30,
        workMinutes: 15,
        crowd: "高",
        fatigue: "中",
        risk: "低",
        fatigueBaseCost: 310,
        riskBaseCost: 120,
        benefitBonus: 780,
        facts: ["入場料2,800円", "雨に強い", "混雑 高", "満足度 高"],
        reason: "費用はかかりますが、天気に左右されず遊びの満足度が高いです。",
        caution: "休日は混雑で滞在満足度が落ちる可能性があります。",
        fit: "予算よりも確実に楽しめることを重視する家族"
      },
      {
        id: "children-center",
        name: "近所の児童館",
        shortName: "児童館",
        paymentCost: 0,
        travelMinutes: 12,
        workMinutes: 10,
        crowd: "中",
        fatigue: "低",
        risk: "低",
        fatigueBaseCost: 110,
        riskBaseCost: 80,
        benefitBonus: 820,
        facts: ["入場料0円", "移動12分", "雨に強い", "負荷 低"],
        reason: "費用・移動・天気リスクのバランスが良く、親の疲労コストを抑えられます。",
        caution: "大型施設ほどの特別感はありません。",
        fit: "短時間で安全に過ごしたい子育て世帯"
      }
    ]
  }
];
